---
 - name: Installing HTTPD
   hosts: redhat
   become: true
   gather_facts: false
   vars:
     pkg: httpd
   tasks:
     - shell: rpm -q httpd | head -n 1
       register: result
     - set_fact:
        result: "{{result.stdout}}"
     - yum:
         name: "{{pkg}}"
         state: latest
       failed_when: "'not installed' not in result.stdout"
